# Generated by Django 5.1.3 on 2024-11-28 12:38

import useraccounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', useraccounts.models.CustomUserManager()),
            ],
        ),
    ]
